[package]
name = "expert-system"
version = "0.1.0"
<<<<<<< HEAD
authors = ["nanderstabel <nanderstabel@gmail.com>"]
=======
authors = ["nanderstabel <nanderstabel@gmail.com>", "pepijnholster <pgaholster@gmail.com>"]
>>>>>>> main
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
