use crate::*;
use permutation_iter::PermutationIter;

use anyhow::{anyhow, Context, Result};
use std::borrow::Borrow;
use std::collections::{HashMap, HashSet};
use std::fmt;
use std::iter::Peekable;
use std::rc::Rc;
use Token::*;

#[derive(Debug, Copy, Clone)]
pub enum Direction {
    UniDirectional,
    BiDirectional,
}

#[derive(Debug, Copy, Clone)]
pub enum Token {
    Implicator(Direction),
    Operator(char),
    Parenthesis(char),
    Bool(bool),
}

#[derive(Default)]
pub struct RuleParser;

impl<'a> RuleParser {
    pub fn new() -> Self {
        RuleParser {}
    }

    fn get_direction<I>(&mut self, lexer: &mut Peekable<I>, c: char) -> Result<Direction>
    where
        I: Iterator<Item = char>,
    {
        if let Some(next) = lexer.next() {
            match (c, next) {
                ('=', '>') => Ok(Direction::UniDirectional),
                ('<', '=') => match lexer.next() {
                    Some('>') => Ok(Direction::BiDirectional),
                    _ => Err(anyhow!("Unable to finish lexing inplicator")),
                },
                _ => Err(anyhow!("Unable to finish lexing inplicator")),
            }
        } else {
            Err(anyhow!("Unable to finish lexing inplicator"))
        }
    }

    pub fn tokenize(&mut self, input: &str) -> Result<Vec<Token>> {
        let mut lexer = input.chars().peekable();
        let mut tokenlist: Vec<Token> = Vec::new();
        while let Some(c) = lexer.next() {
            match c {
                '(' | ')' => tokenlist.push(Parenthesis(c)),
                '!' | '+' | '|' | '^' => tokenlist.push(Operator(c)),
                '=' | '<' => tokenlist.push(Implicator(self.get_direction(&mut lexer, c)?)),
                '0' => tokenlist.push(Bool(false)),
                '1' => tokenlist.push(Bool(true)),
                c if c.is_whitespace() => {}
                _ => return Err(anyhow!("Unexpected character: {}", c)),
            }
        }
        Ok(tokenlist)
    }

    fn get_rule<I>(&mut self, tokenlist: &mut Peekable<I>) -> Result<bool>
    where
        I: Iterator<Item = &'a Token>,
    {
        let antecedent = self.get_operator(tokenlist)?;
        if let Some(implicator) = tokenlist.next() {
            let consequent = self.get_operator(tokenlist)?;
            match implicator {
                Implicator(direction) => match direction {
                    Direction::UniDirectional => Ok(!antecedent | consequent),
                    Direction::BiDirectional => Ok(antecedent == consequent),
                },
                _ => Err(anyhow!("No implicator found")),
            }
        } else {
            Err(anyhow!("Unexpected end of token list"))
        }
    }

    fn get_operator<I>(&mut self, tokenlist: &mut Peekable<I>) -> Result<bool>
    where
        I: Iterator<Item = &'a Token>,
    {
        let mut node = self.get_factor(tokenlist);
        while let Some(Operator(op)) = tokenlist.peek() {
            node = match tokenlist.next() {
                Some(Operator('+')) => Ok(node? & self.get_factor(tokenlist)?),
                Some(Operator('|')) => Ok(node? | self.get_factor(tokenlist)?),
                Some(Operator('^')) => Ok(node? ^ self.get_factor(tokenlist)?),
                _ => Err(anyhow!("Found unexpected operator: {:?}", op)),
            }
        }
        node
    }

    fn get_factor<I>(&mut self, tokenlist: &mut Peekable<I>) -> Result<bool>
    where
        I: Iterator<Item = &'a Token>,
    {
        match tokenlist.next() {
            Some(Parenthesis('(')) => {
                let res = self.get_operator(tokenlist);
                match tokenlist.next() {
                    Some(Parenthesis(')')) => res,
                    _ => Err(anyhow!("Missing closing parenthesis")),
                }
            }
            Some(Operator('!')) => Ok(!self.get_factor(tokenlist)?),
            Some(Bool(b)) => Ok(*b),
            _ => Err(anyhow!("Unexpected end of token list")),
        }
    }

    pub fn evaluate(&mut self, input: &str) -> Result<bool> {
        let tokenlist = self.tokenize(input).context("Could not tokenize input")?;
        self.get_rule(&mut tokenlist.iter().peekable())
            .context("Syntactical error")
    }
}

// TruthTable struct holds the truth table data of an input rule.
// It can be constructed using a PermutationIter. Since the permutations generated by
// PermuationIter is always guaranteed to follow the same pattern, the order of the results
// implicitly holds the propositional data for each entry in the TruthTable. Example:
// `0 => 0` implies index 0b00, results[0]
// `0 => 1` implies index 0b01, results[1]
// `1 => 0` implies index 0b10, results[2]
// `1 => 1` implies index 0b11, results[3]
#[derive(Default, Eq, PartialEq, Hash, Clone)]
pub struct TruthTable {
    pub variables: Vec<char>,
    pub results: Vec<bool>,
}

impl TruthTable {
    pub fn new() -> Self {
        TruthTable {
            variables: Vec::new(),
            results: Vec::new(),
        }
    }
}

impl TryFrom<PermutationIter> for TruthTable {
    type Error = anyhow::Error;

    fn try_from(mut permutation_iter: PermutationIter) -> Result<Self, Self::Error> {
        let mut table = Self::new();
        let mut parser = RuleParser::new();
        for permutation in permutation_iter.by_ref() {
            table.results.push(
                parser
                    .evaluate(&permutation)
                    .context(format!("Failed to evaluate permutation {}", permutation))?,
            );
        }
        table.variables.append(&mut permutation_iter.variables);
        Ok(table)
    }
}

impl fmt::Debug for TruthTable {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let len = self.variables.len();
        for v in &self.variables {
            write!(f, "| {} ", v)?;
        }
        writeln!(f, "| = |")?;
        writeln!(f, "{}|", "|---".repeat(len + 1))?;
        for (i, result) in self.results.iter().enumerate() {
            for b in 0..len {
                write!(
                    f,
                    "| {} ",
                    if i & (1 << (len - 1 - b)) == 0 { 0 } else { 1 }
                )?
            }
            writeln!(f, "| {} |", if *result { 1 } else { 0 })?;
        }
        Ok(())
    }
}

// Structure that maps for all identifiers the related truth tables.
#[derive(Default, Eq, PartialEq)]
pub struct RuleMap {
    map: HashMap<char, HashSet<Rc<TruthTable>>>,
}

impl RuleMap {
    // To insert a new rule in the rulemap Ad-Hoc
    pub fn insert<T>(&mut self, rule: T) -> Result<()>
    where
        T: AsRef<str>,
    {
        let ptr = Rc::new(TruthTable::try_from(PermutationIter::new(rule))?);
        for v in ptr.variables.iter() {
            let tables = self
                .map
                .entry(*v)
                .or_insert_with(|| HashSet::from([Rc::clone(&ptr)]));
            tables.insert(Rc::clone(&ptr));
        }
        Ok(())
    }

    pub fn insert_vec<T>(&mut self, rules: Vec<T>) -> Result<()>
    where
        T: AsRef<str>,
    {
        for rule in rules.iter() {
            self.insert(rule)?
        }
        Ok(())
    }
}

impl<T> TryFrom<Vec<T>> for RuleMap
where
    T: Borrow<str>,
{
    type Error = anyhow::Error;

    fn try_from(rules: Vec<T>) -> Result<Self> {
        let rule_set = rules
            .into_iter()
            .map(|s| TruthTable::try_from(PermutationIter::new(s.borrow())))
            .collect::<Result<Vec<TruthTable>>>()
            .context("Unable to build RuleMap")?;
        let mut map = HashMap::new();
        for rule in rule_set.into_iter() {
            let ptr = Rc::new(rule);
            for v in ptr.variables.iter() {
                let tables = map
                    .entry(*v)
                    .or_insert_with(|| HashSet::from([Rc::clone(&ptr)]));
                tables.insert(Rc::clone(&ptr));
            }
        }
        Ok(RuleMap { map })
    }
}

impl fmt::Debug for RuleMap {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let mut map = self.map.iter().peekable();
        while let Some((k, v)) = map.next() {
            writeln!(f, "{}", k)?;
            let mut table = v.iter().peekable();
            while let Some(t) = table.next() {
                if map.peek().is_none() && table.peek().is_none() {
                    write!(f, "{:?}", t)?;
                } else {
                    writeln!(f, "{:?}", t)?;
                }
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests_truth_table {
    use super::*;

    use anyhow::Result;
    use pretty_assertions::assert_eq;

    #[test]
    fn simple() -> Result<()> {
        let result = TruthTable::try_from(PermutationIter::new("A => Z"))?;
        assert_eq!(result.variables, vec!['A', 'Z']);
        assert_eq!(result.results, vec![true, true, false, true]);
        Ok(())
    }

    #[test]
    fn valid_rule() -> Result<()> {
        let result = TruthTable::try_from(PermutationIter::new("A + B <=> C"))?;
        assert_eq!(result.variables, vec!['A', 'B', 'C']);
        assert_eq!(
            result.results,
            vec![true, false, true, false, true, false, false, true]
        );
        Ok(())
    }

    #[test]
    fn error_invalid_rule() {
        let result = TruthTable::try_from(PermutationIter::new("A = B"));
        assert!(result.is_err());
        assert_eq!(
            result.unwrap_err().to_string(),
            "Failed to evaluate permutation 0 = 0"
        );
    }
}

#[cfg(test)]
mod rule_map {
    use super::*;

    use anyhow::Result;
    use pretty_assertions::assert_eq;

    #[test]
    fn empty() -> Result<()> {
        Ok(())
    }

    #[test]
    fn insert() -> Result<()> {
        Ok(())
    }

    #[test]
    fn insert_vec() -> Result<()> {
        Ok(())
    }
}
