on:
  pull_request:
  push:
    branches:
      - main

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Cargo Test
      run: cargo test -- -Z unstable-options --format json --report-time | cargo2junit > results.xml
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: results.xml
